export type Lang = 'en' | 'de'

export const COPY = {
  en: {
    navDiscover: 'Discover',
    navPricing: 'Pricing',
    navDashboard: 'Dashboard',
    navLogin: 'Login',
    navCta: 'Start Free',
    navOpenApp: 'Open app',
    tierFree: 'FREE',
    tierPremium: 'PREMIUM',

    discoverShortsEyebrow: 'Shorts Niche Discovery',
    discoverShortsHeadline: "Today's top viral Shorts opportunities",
    discoverLongformEyebrow: 'Longform Niche Discovery',
    discoverLongformHeadline: "Today's high-potential Longform opportunities",
    discoverSubline: 'Refreshed daily · Ranked by opportunity score',
    discoverSearchBtn: 'Search Niches',
    discoverSearchingBtn: 'Searching…',
    discoverEmptyTitle: 'No niches match these filters',
    discoverEmptyBody: 'Try widening the subscriber range or relaxing the channel age filter.',
    discoverResetBtn: 'Reset filters',
    discoverShowMore: (n: number) => `Show more (${n} remaining)`,

    filterFormat: 'Format',
    filterSubscriberRange: 'Subscriber range',
    filterChannelAge: 'Channel age',
    filterSortBy: 'Sort by',
    filterSortScore: 'Best score',
    filterSortNewest: 'Newest',
    filterViralTitle: 'Only viral channels',
    filterViralSub: 'spike ≥3× · last 7 days',
    filterAgeAny: 'Any',
    filterAge1mo: '1 mo',
    filterAge3mo: '3 mo',
    filterAge6mo: '6 mo',
    filterAge1yr: '1 yr',

    topNavShorts: 'Shorts',
    topNavLongform: 'Longform',
    topNavSaved: 'Saved',
    topNavSignOut: 'Sign out',
    topNavSigningOut: 'Signing out…',
    topNavAccount: 'Account',
    topNavTierFree: 'Free',
    topNavTierBasic: 'Basic',
    topNavTierPremium: 'Premium ✦',

    detailBack: 'Back',
    detailNotFound: 'Niche not found',
    detailLoadingErr: 'Failed to load this niche.',
    detailVisitYouTube: 'Visit on YouTube',
    statSubscribers: 'Subscribers',
    statChannelAge: 'Channel age',
    statLanguage: 'Language',
    statVideos: 'Total videos',
    statSpike: 'spike',
    statMonths: 'mo',
    statYears: 'yr',
    chartTitle: '30-day spike trend',
    chartEmpty: 'Not enough scan history yet — check back soon.',
    chartMaxSpike: 'Max',
    videosTitle: 'Recent uploads',
    videosLoading: 'Loading recent videos…',
    videosError: 'Could not load recent videos.',
    videosEmpty: 'This channel has no recent videos.',
    videosRetry: 'Try again',
    videosViewsLabel: 'views',

    heroHeadline: "I built this because YouTube research was eating my weekends.",
    heroSub: "NicheSurge scans 230+ small channels every hour and flags the ones spiking before anyone else notices. No keyword guessing, no copy-paste tactics — just the small accounts that started moving.",
    heroBadge: '47 channels spiked in the last hour',
    heroCta: 'Try it free',
    heroCta2: 'How it works',

    socialTrust: 'Trusted by 1,847 creators',
    socialNiches: '3,612 niches scanned this week',
    socialViews: '11.4 billion views processed',

    previewTitle: 'These niches are moving right now.',
    previewSub: 'Sign up free to see channel names and full metrics.',
    previewCta: 'Unlock all results',

    painHeadline: 'Stop guessing. Start finding.',
    painTitle: 'The slow way',
    painItems: [
      'Scrolling YouTube for hours hoping to spot a trend',
      'Copying channels that already peaked two months ago',
      'Finding the niche the day after it stops working',
    ],
    solutionTitle: 'With NicheSurge',
    solutionItems: [
      '230+ channels under 10k subs analysed every hour',
      'Opportunity scores ranked by spike, engagement, saturation',
      "Email alert the moment a niche you're tracking starts moving",
    ],

    featuresTitle: 'Everything you need to dominate a niche',
    featuresPremiumBadge: 'PREMIUM',
    featuresStatusLive: 'Live now',
    featuresStatusSoon: 'Rolling out next week',
    features: [
      { icon: 'bot', tier: 'all', title: 'AI Opportunity Score', desc: 'Composite score weighing spike, engagement, competition and search volume.' },
      { icon: 'clock', tier: 'all', title: 'Hourly Scans', desc: '230+ channels re-analysed every hour so you never miss a spike window.' },
      { icon: 'flame', tier: 'all', title: 'Viral Spike Detection', desc: 'Flags channels with 3× or higher 48-hour view jumps the moment they appear.' },
      { icon: 'heartbeat', tier: 'premium', status: 'live', title: 'AI Niche Health Check', desc: 'One-click verdict on whether a niche is worth entering this week — score plus a strategist-grade paragraph on the risks and the opening.' },
      { icon: 'trend-up', tier: 'premium', status: 'soon', title: 'AI Clone & Twist', desc: 'Claude shows you exactly how to replicate a viral format with your unique spin.' },
      { icon: 'lightbulb', tier: 'premium', title: '5 AI Shorts Ideas', desc: 'Get five ready-to-shoot Shorts ideas, hooks and titles tailored to each spiking niche.' },
      { icon: 'bell', tier: 'premium', status: 'soon', title: 'Early Warning Alerts', desc: 'Email + in-app alert the moment a niche you track starts spiking — before everyone else.' },
    ],

    pricingTitle: 'Pick the plan that fits your week.',
    pricingFree: 'Free',
    pricingBasic: 'Basic',
    pricingPremium: 'Premium',
    pricingFreePrice: '€0',
    pricingBasicPrice: '€9',
    pricingPremiumPrice: '€19',
    pricingPerMonth: '/ mo',
    pricingPerYear: '/ yr',
    pricingToggleMonthly: 'Monthly',
    pricingToggleYearly: 'Yearly',
    pricingYearlySaveBadge: 'Save 17%',
    pricingBasicYearlyPrice: '€90',
    pricingBasicYearlyMonthly: '€7.50 / mo',
    pricingPremiumYearlyPrice: '€190',
    pricingPremiumYearlyMonthly: '€15.83 / mo',
    pricingBestValueBadge: 'Best Value',
    pricingCtaFree: 'Get Started',
    pricingCtaBasic: 'Start Basic',
    pricingCtaPremium: 'Go Premium',
    pricingFreeFeatures: ['Opportunity score visible', 'Top 5 niches per scan', 'Channel name hidden', '3 searches / day'],
    pricingBasicFeatures: [
      'Top 20 niches per scan',
      'Channel names + full metrics',
      'Top 3 viral videos per niche',
      '20 searches / day',
      '10 saved bookmarks',
      'EN + DE markets',
    ],
    pricingPremiumFeatures: [
      'Everything in Basic, plus:',
      'AI Clone & Twist suggestions',
      '5 AI Shorts ideas per niche',
      'AI thumbnail + title concepts',
      'Early Warning spike alerts',
      'AI Niche Health Check',
      '30-day scan history',
      'Unlimited bookmarks + searches',
    ],

    testimonialsTitle: 'Creators who found their niche',
    testimonials: [
      {
        quote: "Found a German 'silent study desk' niche with a 12.4× spike. First Short hit 84,000 views in 6 days. I was scanning manually for months — this saved my weekends.",
        name: 'Marcus T.',
        handle: '@marcust_creates',
        detail: 'Shorts since March 2024 · Berlin',
      },
      {
        quote: "The opportunity score is the only metric I trust now. Bookmarked 14 niches in week one, three of them popped within 10 days. Better hit rate than my last six months of guessing.",
        name: 'Sarah K.',
        handle: '@sarahkcontent',
        detail: 'Long-form essays · Manchester',
      },
      {
        quote: "I'm Lithuanian making German content. The DE filter cut my research to nothing — I get fed niches I'd never have searched for. Two of my last four uploads cleared 50k.",
        name: 'Lukas B.',
        handle: '@lukasbfilms',
        detail: 'Cinematic Shorts · Vilnius',
      },
    ],

    ctaHeadline: 'Find a niche before it gets crowded.',
    ctaButton: 'Start free',

    footerTagline: 'AI-powered YouTube niche discovery.',
    footerLinks: 'Links',
    footerLegal: 'Legal',
    footerPrivacy: 'Privacy',
    footerTerms: 'Terms',
    footerCopyright: '© 2026 NicheSurge',
  },

  de: {
    navDiscover: 'Entdecken',
    navPricing: 'Preise',
    navDashboard: 'Dashboard',
    navLogin: 'Anmelden',
    navCta: 'Kostenlos starten',
    navOpenApp: 'App öffnen',
    tierFree: 'FREE',
    tierPremium: 'PREMIUM',

    discoverShortsEyebrow: 'Shorts-Nischenfinder',
    discoverShortsHeadline: 'Die heißesten Shorts-Nischen heute',
    discoverLongformEyebrow: 'Longform-Nischenfinder',
    discoverLongformHeadline: 'Longform-Nischen mit dem größten Potenzial heute',
    discoverSubline: 'Täglich aktualisiert · Sortiert nach Opportunity-Score',
    discoverSearchBtn: 'Nischen suchen',
    discoverSearchingBtn: 'Suche…',
    discoverEmptyTitle: 'Keine Nischen für diese Filter gefunden',
    discoverEmptyBody: 'Erweitere den Abonnenten-Bereich oder lockere den Kanal-Alter-Filter.',
    discoverResetBtn: 'Filter zurücksetzen',
    discoverShowMore: (n: number) => `Mehr anzeigen (${n} übrig)`,

    filterFormat: 'Format',
    filterSubscriberRange: 'Abonnenten',
    filterChannelAge: 'Kanal-Alter',
    filterSortBy: 'Sortieren nach',
    filterSortScore: 'Bester Score',
    filterSortNewest: 'Neueste',
    filterViralTitle: 'Nur virale Kanäle',
    filterViralSub: 'Spike ≥3× · letzte 7 Tage',
    filterAgeAny: 'Beliebig',
    filterAge1mo: '1 Mo',
    filterAge3mo: '3 Mo',
    filterAge6mo: '6 Mo',
    filterAge1yr: '1 Jahr',

    topNavShorts: 'Shorts',
    topNavLongform: 'Longform',
    topNavSaved: 'Gespeichert',
    topNavSignOut: 'Abmelden',
    topNavSigningOut: 'Wird abgemeldet…',
    topNavAccount: 'Konto',
    topNavTierFree: 'Free',
    topNavTierBasic: 'Basic',
    topNavTierPremium: 'Premium ✦',

    detailBack: 'Zurück',
    detailNotFound: 'Nische nicht gefunden',
    detailLoadingErr: 'Diese Nische konnte nicht geladen werden.',
    detailVisitYouTube: 'Auf YouTube ansehen',
    statSubscribers: 'Abonnenten',
    statChannelAge: 'Kanal-Alter',
    statLanguage: 'Sprache',
    statVideos: 'Videos gesamt',
    statSpike: 'Spike',
    statMonths: 'Mo',
    statYears: 'J',
    chartTitle: '30-Tage-Spike-Trend',
    chartEmpty: 'Noch nicht genug Scan-Historie — schau bald wieder vorbei.',
    chartMaxSpike: 'Max',
    videosTitle: 'Neueste Uploads',
    videosLoading: 'Lade neueste Videos…',
    videosError: 'Videos konnten nicht geladen werden.',
    videosEmpty: 'Dieser Kanal hat keine neuen Videos.',
    videosRetry: 'Erneut versuchen',
    videosViewsLabel: 'Aufrufe',

    heroHeadline: "Ich habe das gebaut, weil YouTube-Recherche meine Wochenenden gefressen hat.",
    heroSub: "NicheSurge scannt stündlich 230+ kleine Kanäle und markiert die, die zu steigen beginnen — bevor es jemand anderes bemerkt. Kein Keyword-Raten, keine Copy-Paste-Taktik.",
    heroBadge: '47 Kanäle sind in der letzten Stunde gestiegen',
    heroCta: 'Kostenlos ausprobieren',
    heroCta2: 'Wie es funktioniert',

    socialTrust: 'Vertraut von 1.847 Creatorn',
    socialNiches: '3.612 Nischen diese Woche gescannt',
    socialViews: '11,4 Milliarden Views verarbeitet',

    previewTitle: 'Diese Nischen steigen gerade.',
    previewSub: 'Kostenlos registrieren, um Kanalnamen und alle Metriken zu sehen.',
    previewCta: 'Alle Ergebnisse freischalten',

    painHeadline: 'Schluss mit Raten. Anfangen zu finden.',
    painTitle: 'Der langsame Weg',
    painItems: [
      'Stundenlang durch YouTube scrollen in der Hoffnung, einen Trend zu entdecken',
      'Kanäle kopieren, die schon vor zwei Monaten ihren Höhepunkt hatten',
      'Die Nische einen Tag nachdem sie nicht mehr funktioniert finden',
    ],
    solutionTitle: 'Mit NicheSurge',
    solutionItems: [
      '230+ Kanäle unter 10k Subs werden stündlich analysiert',
      'Opportunity-Scores nach Spike, Engagement und Sättigung sortiert',
      'E-Mail-Alert in dem Moment, in dem deine getrackte Nische zu steigen beginnt',
    ],

    featuresTitle: 'Alles, was du brauchst, um eine Nische zu dominieren',
    featuresPremiumBadge: 'PREMIUM',
    featuresStatusLive: 'Jetzt verfügbar',
    featuresStatusSoon: 'Nächste Woche verfügbar',
    features: [
      { icon: 'bot', tier: 'all', title: 'KI-Opportunity-Score', desc: 'Kombinierter Score aus Spike, Engagement, Wettbewerb und Suchvolumen.' },
      { icon: 'clock', tier: 'all', title: 'Stündliche Scans', desc: '230+ Kanäle werden jede Stunde neu analysiert, damit du kein Spike-Fenster verpasst.' },
      { icon: 'flame', tier: 'all', title: 'Viral-Spike-Erkennung', desc: 'Markiert Kanäle mit einem 3-fachen oder höheren 48-Stunden-View-Sprung.' },
      { icon: 'heartbeat', tier: 'premium', status: 'live', title: 'KI Niche Health Check', desc: 'Ein Klick und du weißt, ob die Nische diese Woche den Sprung wert ist — Score plus ein strategisch geschriebener Absatz zu Risiken und Chancen.' },
      { icon: 'trend-up', tier: 'premium', status: 'soon', title: 'KI Clone & Twist', desc: 'Claude zeigt dir, wie du ein virales Format mit deinem eigenen Twist replizierst.' },
      { icon: 'lightbulb', tier: 'premium', title: '5 KI Shorts-Ideen', desc: 'Fünf produktionsbereite Shorts-Ideen, Hooks und Titel pro Nische — sofort umsetzbar.' },
      { icon: 'bell', tier: 'premium', status: 'soon', title: 'Frühwarnungen', desc: 'E-Mail- + In-App-Alerts in dem Moment, in dem deine Nische zu steigen beginnt.' },
    ],

    pricingTitle: 'Wähle den Plan, der zu deiner Woche passt.',
    pricingFree: 'Free',
    pricingBasic: 'Basic',
    pricingPremium: 'Premium',
    pricingFreePrice: '€0',
    pricingBasicPrice: '€9',
    pricingPremiumPrice: '€19',
    pricingPerMonth: '/ Monat',
    pricingPerYear: '/ Jahr',
    pricingToggleMonthly: 'Monatlich',
    pricingToggleYearly: 'Jährlich',
    pricingYearlySaveBadge: '17 % sparen',
    pricingBasicYearlyPrice: '€90',
    pricingBasicYearlyMonthly: '€7,50 / Monat',
    pricingPremiumYearlyPrice: '€190',
    pricingPremiumYearlyMonthly: '€15,83 / Monat',
    pricingBestValueBadge: 'Bestes Angebot',
    pricingCtaFree: 'Jetzt starten',
    pricingCtaBasic: 'Basic starten',
    pricingCtaPremium: 'Premium holen',
    pricingFreeFeatures: ['Opportunity-Score sichtbar', 'Top 5 Nischen pro Scan', 'Kanalname versteckt', '3 Suchen / Tag'],
    pricingBasicFeatures: [
      'Top 20 Nischen pro Scan',
      'Kanalnamen + alle Metriken',
      'Top 3 virale Videos pro Nische',
      '20 Suchen / Tag',
      '10 gespeicherte Bookmarks',
      'EN + DE Märkte',
    ],
    pricingPremiumFeatures: [
      'Alles aus Basic, plus:',
      'KI Clone & Twist Vorschläge',
      '5 KI Shorts-Ideen pro Nische',
      'KI Thumbnail- + Titel-Konzepte',
      'Frühwarn-Spike-Alerts',
      'KI Niche Health Check',
      '30-Tage Scan-Historie',
      'Unbegrenzte Bookmarks + Suchen',
    ],

    testimonialsTitle: 'Creator, die ihre Nische gefunden haben',
    testimonials: [
      {
        quote: "Eine deutsche 'silent study desk' Nische mit 12,4× Spike gefunden. Erster Short hat in 6 Tagen 84.000 Views gemacht. Ich habe monatelang manuell gesucht — das hat meine Wochenenden gerettet.",
        name: 'Marcus T.',
        handle: '@marcust_creates',
        detail: 'Shorts seit März 2024 · Berlin',
      },
      {
        quote: 'Der Opportunity-Score ist die einzige Metrik, der ich noch traue. 14 Nischen in der ersten Woche gespeichert, drei davon haben in 10 Tagen abgehoben. Bessere Trefferquote als meine letzten sechs Monate Raterei.',
        name: 'Sarah K.',
        handle: '@sarahkcontent',
        detail: 'Long-form Essays · Manchester',
      },
      {
        quote: 'Ich bin Litauer und mache deutschen Content. Der DE-Filter hat meine Recherche eliminiert — ich bekomme Nischen vorgeschlagen, nach denen ich nie gesucht hätte. Zwei meiner letzten vier Uploads über 50k.',
        name: 'Lukas B.',
        handle: '@lukasbfilms',
        detail: 'Cinematic Shorts · Vilnius',
      },
    ],

    ctaHeadline: 'Finde eine Nische, bevor sie überfüllt ist.',
    ctaButton: 'Kostenlos starten',

    footerTagline: 'KI-gestützte YouTube-Nischen-Entdeckung.',
    footerLinks: 'Links',
    footerLegal: 'Rechtliches',
    footerPrivacy: 'Datenschutz',
    footerTerms: 'AGB',
    footerCopyright: '© 2026 NicheSurge',
  },
} as const

export type CopyKeys = typeof COPY[keyof typeof COPY]
